In [3]:
import numpy as np
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
print(arr1)
print(arr2)
print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)
print(arr1/arr2)
print(arr1@arr2) #actual matrix multiplication

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[19 22]
 [43 50]]


In [5]:
import numpy as np
concatenated_arr=np.concatenate((arr1,arr2),axis=0)
print(concatenated_arr)
print()
concatenated_arr=np.concatenate((arr1,arr2),axis=1)
print(concatenated_arr)
print()

[[1 2]
 [3 4]
 [5 6]
 [7 8]]

[[1 2 5 6]
 [3 4 7 8]]



In [7]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)
transposed_arr=arr.transpose()
print(transposed_arr)
print()

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]



In [13]:
import numpy as np
flattened_arr=arr.flatten()
print(flattened_arr)
print()

[1 2 3 4 5 6 7 8 9]



In [17]:
import numpy as np
a=np.array([1+4j,1+0j,2,3.5,6j])
print("original array")
print(a)
print("checking for a complex number")
print(np.iscomplex(a))
print("checking for a real number")
print(np.isreal(a))
print("checking for a scalar")
print(np.isscalar(3.1)) #scalar checks for only one element
print(np.isscalar([3.1])) #list is group of elements
print()

original array
[1. +4.j 1. +0.j 2. +0.j 3.5+0.j 0. +6.j]
checking for a complex number
[ True False False False  True]
checking for a real number
[False  True  True  True False]
checking for a scalar
True
False



In [21]:
import numpy as np
arr=np.zeros(7)
arr

array([0., 0., 0., 0., 0., 0., 0.])

In [23]:
import numpy as np
arr=np.zeros((2,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [24]:
import numpy as np
arr=np.ones((2,3))
arr

array([[1., 1., 1.],
       [1., 1., 1.]])

In [32]:
import numpy as np
empty1=np.empty((2,3))
empty1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [33]:
import numpy as np
empty1=np.empty((2,7))
empty1

array([[ 0. ,  0.1,  0. , -0.1,  0.8, -0.1,  0.8],
       [-0.3,  1. ,  0. ,  0.8,  0.3,  0.8,  0.1]])

In [34]:
import numpy as np
a=np.array([1,2,3,4,5,5])
print(a)

[1 2 3 4 5 5]


In [35]:
import numpy as np
print(a.dtype)
print(a.ndim)
print(a.shape)
print(a.size)
print(a.itemsize)
print(a.nbytes)

int64
1
(6,)
6
8
48


In [39]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])

print(a.shape)

(6,)


In [40]:
print(a.size)

6


In [41]:
print(a.ndim)

1


In [42]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])

print(a.ndim)

1


In [44]:
import numpy as np
print(np.__version__)

2.0.2


In [ ]:
im